# Generated by Django 5.0.6 on 2026-01-05 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_address_user_birth_date_user_gifts_given_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название вишлиста', max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Описание вишлиста', null=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=False, help_text='Виден ли вишлист другим пользователям', verbose_name='Публичный')),
                ('is_default', models.BooleanField(default=False, help_text='Вишлист по умолчанию для пользователя', verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания вишлиста', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления вишлиста', verbose_name='Дата обновления')),
                ('order', models.IntegerField(default=0, help_text='Порядок сортировки вишлистов', verbose_name='Порядок')),
                ('user', models.ForeignKey(help_text='Владелец вишлиста', on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вишлист',
                'verbose_name_plural': 'Вишлисты',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название желания', max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Описание желания', null=True, verbose_name='Описание')),
                ('link', models.URLField(blank=True, help_text='Ссылка на товар или услугу', null=True, verbose_name='Ссылка')),
                ('image_url', models.URLField(blank=True, help_text='Ссылка на изображение желания', null=True, verbose_name='URL изображения')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена желания', max_digits=10, null=True, verbose_name='Цена')),
                ('currency', models.CharField(default='₽', help_text='Валюта цены', max_length=10, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('active', 'Активное'), ('reserved', 'Зарезервировано'), ('fulfilled', 'Исполнено')], default='active', help_text='Текущий статус желания', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания желания', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления желания', verbose_name='Дата обновления')),
                ('reserved_at', models.DateTimeField(blank=True, help_text='Дата и время резервирования желания', null=True, verbose_name='Дата резервирования')),
                ('gifted_at', models.DateTimeField(blank=True, help_text='Дата и время дарения желания', null=True, verbose_name='Дата дарения')),
                ('order', models.IntegerField(default=0, help_text='Порядок сортировки желаний в вишлисте', verbose_name='Порядок')),
                ('gifted_by', models.ForeignKey(blank=True, help_text='Пользователь, который подарил желание', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifted_wishes', to='users.user', verbose_name='Подарено пользователем')),
                ('reserved_by', models.ForeignKey(blank=True, help_text='Пользователь, который зарезервировал желание', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_wishes', to='users.user', verbose_name='Зарезервировано пользователем')),
                ('user', models.ForeignKey(help_text='Владелец желания', on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='users.user', verbose_name='Пользователь')),
                ('wishlist', models.ForeignKey(help_text='Вишлист, к которому относится желание', on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='wishes.wishlist', verbose_name='Вишлист')),
            ],
            options={
                'verbose_name': 'Желание',
                'verbose_name_plural': 'Желания',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'order'], name='wishes_wish_user_id_6b78e6_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'is_default'], name='wishes_wish_user_id_40b540_idx'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'is_default'), name='unique_default_wishlist_per_user'),
        ),
        migrations.AddIndex(
            model_name='wish',
            index=models.Index(fields=['wishlist', 'order'], name='wishes_wish_wishlis_4669dd_idx'),
        ),
        migrations.AddIndex(
            model_name='wish',
            index=models.Index(fields=['user', 'status'], name='wishes_wish_user_id_79d8ae_idx'),
        ),
        migrations.AddIndex(
            model_name='wish',
            index=models.Index(fields=['status'], name='wishes_wish_status_8d3174_idx'),
        ),
    ]
