# Generated by Django 5.0.6 on 2026-01-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_default_wishlist_per_user',
        ),
        migrations.RemoveIndex(
            model_name='wishlist',
            name='wishes_wish_user_id_40b540_idx',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='is_default',
        ),
    ]
