# Generated by Django 5.0.6 on 2026-01-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_remove_wishlist_unique_default_wishlist_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Виден ли вишлист другим пользователям', verbose_name='Публичный'),
        ),
    ]
