# Generated by Django 5.0.6 on 2026-01-06 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0003_alter_wishlist_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='is_public',
        ),
    ]
