# Generated by Django 5.0.6 on 2026-01-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0004_remove_wishlist_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='description',
        ),
        migrations.AddField(
            model_name='wish',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий к желанию', null=True, verbose_name='Комментарий'),
        ),
    ]
