# Generated by Django 5.0.6 on 2026-01-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0005_remove_wish_description_wish_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='event_date',
            field=models.DateField(blank=True, help_text='Дата события, к которому приурочен вишлист (например, день рождения)', null=True, verbose_name='Дата события'),
        ),
    ]
