# Generated by Django 5.0.6 on 2026-01-05 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='Уникальный идентификатор пользователя в Telegram', unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(help_text='Имя пользователя', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия пользователя', max_length=150, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, help_text='Username пользователя в Telegram', max_length=150, null=True, verbose_name='Username Telegram')),
                ('registration_time', models.DateTimeField(auto_now_add=True, help_text='Дата и время регистрации пользователя', verbose_name='Время регистрации')),
                ('last_visit', models.DateTimeField(auto_now=True, help_text='Дата и время последнего посещения приложения', verbose_name='Время последнего посещения')),
                ('language', models.CharField(default='ru', help_text='Язык интерфейса пользователя', max_length=10, verbose_name='Язык')),
                ('theme_color', models.CharField(default='light', help_text='Цветовая тема приложения', max_length=50, verbose_name='Цвет темы')),
                ('invited_by', models.ForeignKey(blank=True, help_text='Пользователь, который пригласил данного пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to='users.user', verbose_name='Кто пригласил')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-registration_time'],
                'indexes': [models.Index(fields=['telegram_id'], name='users_user_telegra_b51e4c_idx'), models.Index(fields=['registration_time'], name='users_user_registr_5918c0_idx')],
            },
        ),
    ]
