# Generated by Django 5.0.6 on 2026-01-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Адрес проживания пользователя', null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Дата рождения пользователя', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='gifts_given',
            field=models.IntegerField(default=0, help_text='Количество подарков, которые пользователь подарил', verbose_name='Количество подаренных подарков'),
        ),
        migrations.AddField(
            model_name='user',
            name='gifts_received',
            field=models.IntegerField(default=0, help_text='Количество подарков, которые пользователь получил', verbose_name='Количество полученных подарков'),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.TextField(blank=True, help_text='Хобби и интересы пользователя', null=True, verbose_name='Хобби'),
        ),
    ]
