# Generated by Django 5.0.6 on 2026-01-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_birth_date_user_gifts_given_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, help_text='Пользователи, на которых подписан данный пользователь', related_name='subscribers', to='users.user', verbose_name='Подписки'),
        ),
    ]
