# Generated by Django 5.0.6 on 2026-01-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.URLField(blank=True, help_text='URL фотографии профиля пользователя из Telegram', max_length=500, null=True, verbose_name='URL фотографии'),
        ),
    ]
